{
 "title": "Boost Utilization",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "db_bucket", "label": "Database Bucket", "query": "buckets() " },
   {
    "name": "ec_hostname",
    "label": "Appliance",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"${db_bucket}\",\n    tag: \"hostname\",\n    predicate: (r) => true,\n)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "This example code serves to demonstrate the possibilities in\nretrieving telemetry data from Orchestrator and EdgeConnect and\nvisuzalize it. The demo is simple to run, however, modifying\nand/or incorporating components of this work into your own solution\nrequires a greater understanding of Python, Docker, InfluxDB,\nGrafana, and Redis.\n\n\nAll of these components are not necessarily required for developing\nyour own solution as there may be pieces of data you don't need\nto collect, some additional others that you want to add,\nsubstitude alternative tools for task queuing, database, and\nvisualization or alerting needs.",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"color:red;text-align:center;\">THIS DEMO IS NOT MEANT TO BE A PRODUCTION MONITORING SOLUTION</h1>"
   }
  },
  {
   "title": "Boost Bytes - Normalized %",
   "type": "heatmap",
   "description": "Calculating Boost Utilization normalized over all appliances. Calculates percentage utilization comparing real utilization against configured max on appliance. Administrator would need to determine if an appliance reaching high utilization has enough resources and/or large enough hardware to support increasing the maximum value if running high.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "query": "boost = from(bucket: \"ECTELEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"boost_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"boost_bytes\")\n  |> map(fn: (r) => ({r with _value: r._value / 8}))\n\nconfigured = from(bucket: \"ECTELEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"boost_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"boost_configured_kbps\")\n  |> map(fn: (r) => ({r with _value: r._value * 1000}))\n\n// Calculate Utilization of Boost Used vs Configured Boost\njoin(tables:{boost:boost, configured:configured}, on:[\"_time\", \"hostname\"])\n  |> map(fn:(r) => ({ _time: r._time, hostname: r.hostname,\n   _value: float(v: r._value_boost) / float(v: r._value_configured) }))\n  |> yield(name: \"boost\")"
    }
   ]
  },
  {
   "title": "Boost Bytes - Actual",
   "type": "heatmap",
   "description": "Actual Boost Utilization over all appliances. Keep in mind some appliances may be capable of much higher Boost throughputs so good to reference the Normalized chart when comparing appliances against each other",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "query": "from(bucket: \"ECTELEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"boost_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"boost_bytes\")\n  |> keep(columns: [\"_value\", \"_time\", \"boost_bytes\",\"hostname\"])"
    }
   ]
  },
  {
   "title": "Total Boost Bytes",
   "type": "piechart",
   "description": "Cumulative sum of Boosted Bytes per appliance in the fabric",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ECTELEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"boost_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"boost_bytes\")\n  |> cumulativeSum()\n  |> keep(columns: [\"_value\", \"_time\", \"boost_bytes\",\"hostname\"])"
    }
   ]
  },
  {
   "title": "Time Insufficient Boost",
   "type": "timeseries",
   "description": "Monitor for any appliances logging time where insufficient Boost was experienced between traffic matching Boost and hitting the configured maximum on the appliance",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"ECTELEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"boost_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"seconds_not_boosted_in_minute\")"
    }
   ]
  }
 ]
}